spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?serverTimezone=Asia/Seoul
    username: root
    password: choiwnsgh1a

  jpa:
    hibernate:
      ddl-auto: update    # ??: ?? ??? ?? DB ???? ???? ???/??? ???.
    show-sql: true        # ??? ??? ?? SQL? ????? ???? ?????.
    properties:
      hibernate:
        format_sql: true  # SQL? ??? ???? ?????.